spring:
  application:
    name: api
  datasource:
    hikari:
      maximum-pool-size: 100
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ecommerce-db?profileSQL=true
    username: shlee
    password: shlee123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

logging:
  level:
    root: info