spring:
  application:
    name: batch
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  datasource:
    hikari:
      maximum-pool-size: 200
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ecommerce-db?profileSQL=true
    username: shlee
    password: shlee123

logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
#    org.springframework.jdbc.core.StatementCreatorUtils: debug

prometheus:
  job:
    name: spring-batch
  pushgateway:
    url: localhost:9091